import React from 'react'
import Logo from '../components/logo'
import styles from '../styles/Home.module.css'
import Head from 'next/head'
import Image from 'next/image'

import Link from 'next/link'
import Login from '../components/Login';
import { useRouter } from 'next/router';
import Modal from 'react-modal'
import { signIn, signOut, useSession } from 'next-auth/react'




Modal.setAppElement('#__next')


function index() {
	const router = useRouter()
	const { data: session, status } = useSession()
	console.log({ session, status })
	session && router.replace("/home/peergroups")
	return (
		<div className={styles.main_div}>

			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
					integrity="sha512-9usAa10IRO0HhonpyAIVpjrylPvoDwiPUiKdWk5t3PyolY1cOd4DSE0Ga+ri4AuTroPR5aQvXU9xC6qOPnzFeg=="
					crossorigin="anonymous" referrerpolicy="no-referrer" />
				<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css"
					crossorigin="anonymous" />
				<link rel="icon" href="/peerllogo.svg" />
				<title>PEERL</title>
				<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
					integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
					crossorigin="anonymous" />
				<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
					integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
					crossorigin="anonymous"></script>
				<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
					integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
					crossorigin="anonymous"></script>
				<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
					integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
					crossorigin="anonymous"></script>
			</Head>

			<div className={styles.header_wrapper}>
				<Logo class={styles.logo}></Logo>
				<nav className={styles.navbar}>
					<a>about</a>
					<a>platform</a>
					{/*
			<Link href={`/?login=${true}`} as={`/login`}>
			<a>login</a>
			</Link> */}
					<Link href='/api/auth/signin'>
						<a>login</a>
					</Link>

				</nav>
				<Link href={`/?signup=${true}`} as={`/signup`}>
					<a className={styles.signup_btn}>sign up</a>
				</Link>

			</div>
			{/* <div className={styles.plane_2}>
		<Image src="/Hero/planeR2L.svg" alt="Circle 1" width={50} height={50}></Image>
	</div>
	<div className={styles.plane_1}>
		<Image src="/Hero/planeL2R.svg" alt="Circle 1" width={75} height={75}></Image>
	</div> */}
			{/* <div className={styles.chute_res}>
		<Image src="/Hero/chute.svg" alt="Circle 1" width={50} height={50}></Image>
	</div> */}
			
			<div className={styles.firstdivsection}>
				<div className={styles.peerl_ilstrn}>
					<Image src="/Hero/CentralGraphics.svg" alt="PEERL Logo" width={500} height={300} />
				</div>
	
				<div className={styles.tagline_wrapper}>
					<p className={styles.primary_txt}>
						A Place you were looking for...
					</p>
					<p className={styles.secondary_txt}>
						you found the place where you can get anything to start your<br></br>journey of learning
					</p>
					<button className={styles.cta_btn}>view trending rooms</button>
					<div className={styles.circle_1}>
						<Image src="/Hero/patternCircle1.svg" alt="Circle 1" width={1000} height={1000}></Image>
					</div>
					<div className={styles.circle_2}>
						<Image src="/Hero/patternCircle1.svg" alt="Circle 1" width={800} height={800}></Image>
					</div>
					<div className={styles.circle_3}>
						<Image src="/Hero/patternCircle3.svg" alt="Circle 1" width={100} height={100}></Image>
					</div>
				</div>
			</div>



			{/* <Modal className={styles.login_modal} overlayClassName={styles.overlay} isOpen={!!router.query.login}
		onRequestClose={()=> router.push('/')}
		contentLabel="Post modal"
		>

		<Login custom_styles={{label_input_wrapper: styles.label_input_wrapper, login_form: styles.login_form,
			login_btn: styles.login_btn, label: styles.form_label, input: styles.form_input}} />
	</Modal> */}

			{/* <Modal isOpen={!!router.query.signup} onRequestClose={()=> router.push('/')}
		contentLabel="Post modal"
		>

		<Login />
	</Modal> */}

			<div className={styles.second_main_div}>
				<div className={styles.left_section}>
					<Image src="/Hero/lpsec1.png" alt="Circle 1" width={600} height={600}></Image>
				</div>
				<div className={styles.right_section}>
					<div className={styles.section2topheading}>
						<p>Peerl, huh?</p><span className={styles.secondsectionimage}>
							<Image src="/Hero/section2small.png" alt="" width={35} height={35}></Image>
						</span>
					</div>
					<h2>A peer to peer learning studio</h2>
					<div>
						<p className={styles.lightpara}>
							PEERL stands as a platform where the one who is willing to teach or share knowledge and the one who
							is in search of knowledge or an avid learner can come together and communicate and collaborate in
							order to create a one-stop solution for future learners hence making the process of learning
							convenient.
						</p>
					</div>
				</div>

			</div>

			<div className={styles.third_main_div}>
				<div className={styles.third_left_section}>
					<div className={styles.section3topheading}>
						<p>Why Peerl?</p><span className={styles.thirdsectionimage}>
							<Image src="/Hero/section2small.png" alt="" width={35} height={35}></Image>
						</span>
					</div>
					<h2>Learning Made Simple & Easy</h2>
					<div>
						<p className={styles.lightpara}>
							Everyone has a different learning pace or strategy which they discover as they move on with their
							curiosity. Information should be free and available for all and should not be under the control of
							one central authority, it belongs to the community as a whole and learning should happen without any
							disturbance in the momentum of one’s flow in learning
						</p>
					</div>
				</div>
				<div className={styles.third_right_section}>
					<Image src="/Hero/thirdsectionimage.png" alt="Circle 1" width={600} height={600}></Image>
				</div>

			</div>

			<div className={styles.second_main_div}>
				<div className={styles.left_section}>
					<Image src="/Hero/lpsec1.png" alt="Circle 1" width={600} height={600}></Image>
				</div>
				<div className={styles.right_section}>
					<div className={styles.section2topheading}>
						<p>Peerl, huh?</p><span className={styles.secondsectionimage}>
							<Image src="/Hero/section2small.png" alt="" width={35} height={35}></Image>
						</span>
					</div>
					<h2>A peer to peer learning studio</h2>
					<div>
						<p className={styles.lightpara}>
							PEERL stands as a platform where the one who is willing to teach or share knowledge and the one who
							is in search of knowledge or an avid learner can come together and communicate and collaborate in
							order to create a one-stop solution for future learners hence making the process of learning
							convenient.
						</p>
					</div>
				</div>

			</div>


			{/* <div className={styles.fourthsection}>
		<div className={styles.thirdsection_part1}>
			<Image src="/Hero/breaksectionimage.png" alt="Circle 1" width={600} height={600}></Image>
		</div>
		<div className={styles.thirdsection_part2}>
			<div className={styles.card1}>
				<div className={styles.card__icon}></div>
				<p className={styles.card__exit}></p>
				<h2 className={styles.card__title}>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</h2>
				<p className={styles.card__apply}>
					<a className={styles.card__link} href="#">Apply Now <i className={styles.fa-arrow-right, styles.fas}></i></a>
				</p>
			</div>
			<div className={styles.card2}></div>
			<div className={styles.card3}></div>
		</div>
	</div> */}

		</div>

	)
}

export default index