import React from 'react'
import Logo from '../components/logo'
import styles from '../styles/Home.module.css'
import Head from 'next/head'
import Image from 'next/image'



function index() {
	return (
		<div className={styles.main_div}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/peerllogo.svg" />
				<title>PEERL</title>
			</Head>

			<div className={styles.header_wrapper}>
				<Logo class={styles.logo}></Logo>
				<nav className={styles.navbar}>
					<a>about</a>
					<a>platform</a>
					<a>login</a>
				</nav>
				<a className={styles.signup_btn}>sign up</a>
			</div>

			<div className={styles.peerl_ilstrn}>
				<Image src="/Hero/CentralGraphics.svg" alt="PEERL Logo" width={500} height={300} />
			</div>

			<div className={styles.tagline_wrapper}>
				<p className={styles.primary_txt}>
				A Place you was looking for...
				</p>
				<p className={styles.secondary_txt}>
				you found the place where you can get anything to start your<br></br>journey of learning
				</p>
				<button className={styles.cta_btn}>view trending rooms</button>
			</div>
			<div class="circle_1">
				
			</div>

		</div>
	)
}

export default index
