import { getSession, signOut } from 'next-auth/react';
import { useRouter } from 'next/router';
import React, { useState } from 'react';
import useAuth from '../../hooks/useAuth';
import styles from '../../styles/HomePage.module.css';
import Image from 'next/image'
import Head from 'next/head'
import Link from 'next/link'
import CommonHeader from '../../components/CommonHeader';

function homepage() {
  const router = useRouter()
  console.log(router.query.options)
  const context = router.query.options
  const comp = (
    <div className={styles.main_div}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/peerllogo.svg" />
        <title>PEERL</title>
      </Head>
      {/* <button onClick={(e) => signOut({ callbackUrl: 'http://localhost:3000/' })}>sign out</button> */}

      {/* <header className={styles.header_panel}>
        <button className={styles.menu_btn}></button>
        <div className={styles.logo_context_header_wrapper}>
          <div className={styles.logo_wrapper_ext}>
            <div className={styles.logo_wrapper}>
              <Image src="/PeerlLogo2.svg" alt="PEERL Logo" layout='fill' quality="100" />
            </div>
          </div>
          <p className={styles.context_header}>peer group</p>
        </div>
        <div className={styles.btns_container}>
          <button className={styles.search_button}></button>
          <button className={styles.notification_button}></button>
          <button className={styles.settings_btn}></button>
          <div className={styles.user_capsule}>
            <div className={styles.avtr_image}>
              <Image src='/empty_face.svg' layout='fill'></Image>
            </div>
            <div className={styles.avtr_content}>
              <p className={styles.user_name}>alby</p>
              <p className={styles.user_rank}>expert</p>
            </div>
          </div>
        </div>
      </header> */}

      <CommonHeader />

      <div className={styles.body_flex_wrapper}>
        {context=='peergroups' && <Peergroup_comp />}
        {context=='rooms' && <Rooms_comp />}
        <nav className={styles.nav_panel}>
          <Link href="/home/peergroups">
            <div className={styles.link_group}>
              <div className={styles.link_icon_peergroups}></div>
              <a className={styles.link_text}>peer groups</a>
            </div>
          </Link>
          <Link href="/home/rooms">
            <div className={styles.link_group}>
              <div className={styles.link_icon_rooms}></div>
              <a className={styles.link_text}>rooms</a>
            </div>
          </Link>
          <Link href="/home/subscriptions">
            <div className={styles.link_group}>
              <div className={styles.link_icon_subscriptions}></div>
              <a className={styles.link_text}>subscriptions</a>
            </div>
          </Link>
          <Link href="/home/notebooks">
            <div className={styles.link_group}>
              <div className={styles.link_icon_notebooks}></div>
              <a className={styles.link_text}>notebooks</a>
            </div>
          </Link>
          <Link href="/trendingrooms">
            <div className={styles.link_group}>
              <div className={styles.link_icon_trendingrooms}></div>
              <a className={styles.link_text}>trending rooms</a>
            </div>
          </Link>
        </nav>
      </div>
    </div>)
  return useAuth(comp)
  // return comp
}

export default homepage;





function Peergroup_comp(props) {

  const peergroup_comp_jsx = (
    <div className={styles.rooms_activities_wrapper}>

      <div className={styles.recent_activites_header_wrapper}>
        <p>recent activities</p>
        <div className={styles.activities_container}>
          <div className={styles.activity_rect}>
          </div>
          <div className={styles.activity_rect}>
          </div>
          <div className={styles.activity_rect}>
          </div>
          <div className={styles.activity_rect}>
          </div>
          <div className={styles.activity_rect}>
          </div>
        </div>
      </div>

      <div className={styles.rooms_header_wrapper}>
        <p>rooms joined</p>
        <div className={styles.rooms_container}>

          <div className={styles.room_box}>
          </div>
          <div className={styles.room_box}>
          </div>
          <div className={styles.room_box}>
          </div>
        </div>
      </div>
    </div>
  )
  return peergroup_comp_jsx
}




function Rooms_comp(props) {
  const rooms_comp_jsx = (
    <div className={styles.rooms_activities_wrapper}>

      <div className={styles.recent_activites_header_wrapper}>
        <p>recent activities</p>
        <div className={styles.activities_container}>

          <div className={styles.activity_rect}>
          </div>
          <div className={styles.activity_rect}>
          </div>
          <div className={styles.activity_rect}>
          </div>
          <div className={styles.activity_rect}>
          </div>
          <div className={styles.activity_rect}>
          </div>
        </div>
      </div>

      <div className={styles.rooms_header_wrapper}>
        <p>rooms created</p>
        <div className={styles.rooms_container}>
          <div className={styles.create_room_div}>
          </div>
          <div className={styles.room_box}>
          </div>
          <div className={styles.room_box}>
          </div>
          <div className={styles.room_box}>
          </div>
        </div>
      </div>
    </div>
  )
  return rooms_comp_jsx
}

function Subs_comp(props) {

}

function Notebooks_comp(props) {

}


// function getServerSideProps(context){

// }


